fix(ci): temporarily pin matrix to Node 16 on Ubuntu (#113)
* update to use LTS Node 18

- Node 14 [fails to install](https://github.com/agilgur5/react-signature-canvas/actions/runs/12562533381/job/35023139557?pr=112)
  - ```txt
    Run actions/setup-node@v3
    Attempting to download 14.x...
    Not found in manifest. Falling back to download directly from Node
    Error: Unable to find Node version '14.x' for platform darwin and architecture arm64.
    ```

- keep Node 16 for now, although it is out-of-support
  - ensure continuous range testing; should bump that later too

* try 16.x on Ubuntu only for now

- that one [passed](https://github.com/agilgur5/react-signature-canvas/actions/runs/12562533381/job/35023139677)
- 18.x and other 16.x versions failed to install `node-canvas`, c.f. PR comment